export const QRColums = (agGridRowDrag) => [
  {
    headerName: 'ID',
    field: 'id',
    agGridRowDrag,
    filter: 'agNumberColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'Workspace',
    field: 'workspace',
    agGridRowDrag,
    filter: 'agTextColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'Invoice Number',
    field: 'invoice_number',
    agGridRowDrag,
    filter: 'agTextColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'Invoice Date',
    field: 'invoice_date',
    agGridRowDrag,
    filter: 'agDateColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'seller Gstin',
    field: 'seller_gstin',
    agGridRowDrag,
    filter: 'agTextColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'Buyer Gstin',
    field: 'buyer_gstin',
    agGridRowDrag,
    filter: 'agTextColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'Document Type',
    field: 'document_type',
    agGridRowDrag,
    filter: 'agTextColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'Total Amount',
    field: 'total_amount',
    agGridRowDrag,
    filter: 'agNumberColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'Irn',
    field: 'irn',
    agGridRowDrag,
    filter: 'agTextColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'Irn Date',
    field: 'irn_date',
    agGridRowDrag,
    filter: 'agDateColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'Items Count',
    field: 'items_count',
    agGridRowDrag,
    filter: 'agNumberColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'Hsn Code',
    field: 'hsn_code',
    agGridRowDrag,
    filter: 'agTextColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'Nic Sign',
    field: 'nic_sign',
    agGridRowDrag,
    filter: 'agTextColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'QR Detected',
    field: 'qr_detected',
    agGridRowDrag,
    filter: 'agTextColumnFilter',
    chartDataType: 'category',
  },
  // Meta Data
  {
    headerName: 'Filename',
    field: 'filename',
    agGridRowDrag,
    filter: 'agTextColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'S3 Url',
    field: 's3_url',
    agGridRowDrag,
    filter: 'agTextColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'Page Image Link',
    field: 'page_image_link',
    agGridRowDrag,
    filter: 'agTextColumnFilter',
    chartDataType: 'category',
  },
  // ./Fin - Meta Data
  {
    headerName: 'Row Updated At',
    field: 'row_updated_at',
    agGridRowDrag,
    filter: 'agDateColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'Extra Information',
    field: 'extra_information',
    agGridRowDrag,
    filter: 'agTextColumnFilter',
    chartDataType: 'category',
  },
];
