trigger:
  - development

pool:
  vmImage: ubuntu-latest

variables:
  - name: webappname
    value: finkraft-client
  - name: azSub
    value: "3a02d4a0-ea7b-40e2-b5ec-103f9f9fcb03"

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: UseNode@1
            inputs:
              version: '16.x'

          - script: "yarn install"

        #  - script: "yarn test"

          - script: "yarn build"

          - publish: "build"
            artifact: "reactapp"

  - stage: Development
    dependsOn: Build
    jobs:
      - job: Deploy
        steps:
          - download: current
            artifact: "reactapp"

          - task: AzureStaticWebApp@0
            inputs:
              skip_app_build: true
              output_location: "$(Pipeline.Workspace)/reactapp"
              azure_static_web_apps_api_token: '14184dd039707e3098940a7bef1c1367a6b08376fd51300ac34d70be3007837e1-1d64242d-b2f6-42c3-8c35-9b3dc447c3fb00388840'