trigger:
  - development

pool:
  vmImage: ubuntu-latest

variables:
  - group: "Dev Env"
  - name: webappname
    value: finkraft-client
  - name: azSub
    value: "3a02d4a0-ea7b-40e2-b5ec-103f9f9fcb03"
  - name: resourceGroupName
    value: MVP

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: UseNode@1
            inputs:
              version: '16.x'

          - script: "yarn install"

     #     - script: "yarn test"

          - script: "yarn build"

          - publish: "build"
            artifact: "reactapp"

  - stage: Development
    dependsOn: Build
    jobs:
      - job: Deploy
        steps:
          - download: current
            artifact: "reactapp"

          - task: AzureAppServiceSettings@1
            inputs:
              appName: $(webappname)
              resourceGroupName: $(resourceGroupName)
              azureSubscription: $(azSub)
              appSettings: |
                [
                  {
                    "name": "REACT_APP_AG_GRID_LICENCE_KEY",
                    "value": "$(REACT_APP_AG_GRID_LICENCE_KEY)",
                    "slotSetting": false
                  },
                  {
                    "name": "REACT_APP_BACKEND_API",
                    "value": "$(REACT_APP_BACKEND_API)",
                    "slotSetting": false
                  },
                  {
                    "name": "REACT_APP_DROMO_FRONTEND_API_KEY",
                    "value": "$(REACT_APP_DROMO_FRONTEND_API_KEY)",
                    "slotSetting": false
                  },
                  {
                    "name": "AWS_SDK_LOAD_CONFIG",
                    "value": "$(AWS_SDK_LOAD_CONFIG)",
                    "slotSetting": false
                  },
                  {
                    "name": "ENCRYPTION_KEY",
                    "value": "$(ENCRYPTION_KEY)",
                    "slotSetting": false
                  }
                ]

          - task: AzureRmWebAppDeployment@4
            inputs:
              WebAppName: $(webappname)
              azureSubscription: $(azSub)
              packageForLinux: "$(Pipeline.Workspace)/reactapp"
              DeploymentType: zipDeploy
              RemoveAdditionalFilesFlag: true
              StartupCommand: "pm2 serve /home/site/wwwroot --no-daemon --spa"
          

