export const EwbColums = (agGridRowDrag) => [
  {
    headerName: 'ID',
    field: 'id',
    agGridRowDrag,
    filter: 'agNumberColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'File Id',
    field: 'fileId',
    agGridRowDrag,
    filter: 'agTextColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'EWB Number',
    field: 'ewbNumber',
    agGridRowDrag,
    filter: 'agTextColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'EWB Date',
    field: 'ewbDate',
    agGridRowDrag,
    filter: 'agTextColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'Doc Number',
    field: 'docNumber',
    agGridRowDrag,
    filter: 'agTextColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'Doc Date',
    field: 'docDate',
    agGridRowDrag,
    filter: 'agTextColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'GeneratedBy',
    field: 'generatedBy',
    agGridRowDrag,
    filter: 'agTextColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'From',
    field: 'from',
    agGridRowDrag,
    filter: 'agTextColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'To',
    field: 'to',
    agGridRowDrag,
    filter: 'agTextColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'Buyer GSTIN',
    field: 'buyerGSTIN',
    agGridRowDrag,
    filter: 'agTextColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'Status',
    field: 'status',
    agGridRowDrag,
    filter: 'agTextColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'No Of Items',
    field: 'noOfItems',
    agGridRowDrag,
    filter: 'agTextColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'Main HSN Code',
    field: 'mainHSNCode',
    agGridRowDrag,
    filter: 'agTextColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'Hsn Desc',
    field: 'hsnDesc',
    agGridRowDrag,
    filter: 'agTextColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'Total Invoice Value',
    field: 'totalInvoiceValue',
    agGridRowDrag,
    filter: 'agTextColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'Valid Till Date',
    field: 'validTillDate',
    agGridRowDrag,
    filter: 'agTextColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'Mode Of Gen',
    field: 'modeOfGen',
    agGridRowDrag,
    filter: 'agTextColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'Row Update Date',
    field: 'rowUpdateDate',
    agGridRowDrag,
    filter: 'agTextColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'CreatedBy',
    field: 'createdBy',
    agGridRowDrag,
    filter: 'agTextColumnFilter',
    chartDataType: 'category',
  },
];
