export const GSTR2AColums = (agGridRowDrag) => [
  {
    headerName: 'ID',
    field: 'id',
    agGridRowDrag,
    filter: 'agNumberColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'File Id',
    field: 'fileId',
    agGridRowDrag,
    filter: 'agTextColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'Invoice Number',
    field: 'invoice_number',
    agGridRowDrag,
    filter: 'agTextColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'Invoice Date',
    field: 'invoice_date',
    agGridRowDrag,
    filter: 'agDateColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'Seller Gstin',
    field: 'seller_gstin',
    agGridRowDrag,
    filter: 'agTextColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'Buyer Gstin',
    field: 'buyer_gstin',
    agGridRowDrag,
    filter: 'agTextColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'Filing Period',
    field: 'filing_period',
    agGridRowDrag,
    filter: 'agDateColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'Document Type',
    field: 'document_type',
    agGridRowDrag,
    filter: 'agTextColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'Original Invoice Number',
    field: 'original_invoice_number',
    agGridRowDrag,
    filter: 'agTextColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'Original Invoice Date',
    field: 'original_invoice_date',
    agGridRowDrag,
    filter: 'agDateColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'Total Amount',
    field: 'total_amount',
    agGridRowDrag,
    filter: 'agNumberColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'Igst',
    field: 'igst',
    agGridRowDrag,
    filter: 'agNumberColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'Cgst',
    field: 'cgst',
    agGridRowDrag,
    filter: 'agNumberColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'Sgst',
    field: 'sgst',
    agGridRowDrag,
    filter: 'agNumberColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'Total Gst',
    field: 'total_gst',
    agGridRowDrag,
    filter: 'agNumberColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'Taxable Amount',
    field: 'taxable_amount',
    agGridRowDrag,
    filter: 'agNumberColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'Tax Rate',
    field: 'tax_rate',
    agGridRowDrag,
    filter: 'agNumberColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'Irn',
    field: 'irn',
    agGridRowDrag,
    filter: 'agTextColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'Irn Date',
    field: 'irn_date',
    agGridRowDrag,
    filter: 'agDateColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'Row Updated At',
    field: 'row_updated_at',
    agGridRowDrag,
    filter: 'agDateColumnFilter',
    chartDataType: 'category',
  },
  {
    headerName: 'Extra Information',
    field: 'extraColumns',
    agGridRowDrag,
    filter: 'agTextColumnFilter',
    chartDataType: 'category',
  },
];
